### ISSUE TITLE
redis-namespace missing from gemspec

### ISSUE THREAD

**Issue by twelvelabs** [rossta/seymour#2]
redis.rb has `require 'redis-namespace'` at the top, but the dependency is commented out of the gemspec - causing a LoadError when including seymour.

**Comment by rossta** [comment]
Thanks for reporting. When I added support for sorted sets, it was necessary to pull from redis-namespace edge in the Gemfile separately. Now that redis-namespace has been bumped, I was able to add it back to the gemspec. You should be able to update and use it now.
